version: '3.1'
services:
  app:
    container_name: batch-file-collector
    image: batch-file-collector
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
        - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
